apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquiryBoard
  labels:
    app: inquiryBoard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquiryBoard
  template:
    metadata:
      labels:
        app: inquiryBoard
    spec:
      containers:
        - name: inquiryBoard
          image: username/inquiryBoard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5